'use client';

import { Calendar, Clock, TrendingUp, Download, AlertCircle } from 'lucide-react';
import { formatTimeUntil, formatQuality, type VisibilityData } from '@/hooks/useVisibility';

interface ObservationWindowsProps {
  data: VisibilityData | null;
  loading?: boolean;
  error?: string | null;
}

export default function ObservationWindows({
  data,
  loading = false,
  error = null,
}: ObservationWindowsProps) {
  if (loading) {
    return (
      <div className="bg-white border border-gray-200 rounded-lg p-6 animate-pulse">
        <div className="h-6 bg-gray-200 rounded w-1/3 mb-4"></div>
        <div className="space-y-3">
          {[1, 2, 3].map((i) => (
            <div key={i} className="h-20 bg-gray-200 rounded"></div>
          ))}
        </div>
      </div>
    );
  }

  if (error || !data) {
    return (
      <div className="bg-blue-50 border border-blue-200 rounded-lg p-6">
        <div className="flex items-start gap-3">
          <AlertCircle className="h-5 w-5 text-blue-600 flex-shrink-0 mt-0.5" />
          <div>
            <h3 className="font-semibold text-blue-900 mb-1">Location Required</h3>
            <p className="text-sm text-blue-700">
              Set your location to see upcoming observation windows.
            </p>
          </div>
        </div>
      </div>
    );
  }

  const windows = data.forecast.upcomingWindows || [];

  // Generate .ics file content for calendar
  const generateICSFile = (window: typeof windows[0], isoId: string) => {
    const start = new Date(window.start);
    const end = new Date(window.end);

    const formatICSDate = (date: Date) => {
      return date.toISOString().replace(/[-:]/g, '').split('.')[0] + 'Z';
    };

    const icsContent = [
      'BEGIN:VCALENDAR',
      'VERSION:2.0',
      'PRODID:-//ISO Tracker//Observation Window//EN',
      'BEGIN:VEVENT',
      `UID:${isoId}-${start.getTime()}@isotracker.org`,
      `DTSTAMP:${formatICSDate(new Date())}`,
      `DTSTART:${formatICSDate(start)}`,
      `DTEND:${formatICSDate(end)}`,
      `SUMMARY:Observe ${isoId} (${formatQuality(window.quality).text} conditions)`,
      `DESCRIPTION:Observation window for interstellar object ${isoId}\\nMax Altitude: ${window.maxAltitude.toFixed(1)}°\\nQuality: ${formatQuality(window.quality).text}\\nDuration: ${window.duration.toFixed(0)} minutes\\n\\nGenerated by ISO Tracker (isotracker.org)`,
      `LOCATION:Observer Location`,
      'END:VEVENT',
      'END:VCALENDAR',
    ].join('\r\n');

    return icsContent;
  };

  const downloadICS = (window: typeof windows[0], isoId: string) => {
    const icsContent = generateICSFile(window, isoId);
    const blob = new Blob([icsContent], { type: 'text/calendar;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `observation-${isoId}-${new Date(window.start).toISOString().split('T')[0]}.ics`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="bg-white border border-gray-200 rounded-lg p-6">
      {/* Header */}
      <div className="flex items-center justify-between mb-4">
        <div className="flex items-center gap-2">
          <Calendar className="h-5 w-5 text-gray-600" />
          <h3 className="text-lg font-semibold text-gray-900">
            Upcoming Observation Windows
          </h3>
        </div>
        <span className="text-sm text-gray-500">
          Next {windows.length} opportunities
        </span>
      </div>

      {/* Windows List */}
      {windows.length === 0 ? (
        <div className="text-center py-8">
          <AlertCircle className="h-12 w-12 text-gray-400 mx-auto mb-3" />
          <p className="text-gray-600 font-medium mb-1">No Upcoming Windows</p>
          <p className="text-sm text-gray-500">
            This object is not visible from your location in the next {data.forecastPeriod.days} days.
          </p>
        </div>
      ) : (
        <div className="space-y-3">
          {windows.map((window, index) => {
            const startDate = new Date(window.start);
            const endDate = new Date(window.end);
            const { text: qualityText, color: qualityColor } = formatQuality(window.quality);
            const timeUntil = formatTimeUntil(window.start);

            return (
              <div
                key={index}
                className="border border-gray-200 rounded-lg p-4 hover:bg-gray-50 transition-colors"
              >
                {/* Window Header */}
                <div className="flex items-start justify-between mb-3">
                  <div className="flex-grow">
                    <div className="flex items-center gap-2 mb-1">
                      <h4 className="font-semibold text-gray-900">
                        {startDate.toLocaleDateString(undefined, {
                          weekday: 'long',
                          month: 'long',
                          day: 'numeric',
                        })}
                      </h4>
                      <span className={`px-2 py-0.5 rounded-full text-xs font-medium ${
                        window.quality === 'excellent' ? 'bg-green-100 text-green-800' :
                        window.quality === 'good' ? 'bg-blue-100 text-blue-800' :
                        window.quality === 'fair' ? 'bg-yellow-100 text-yellow-800' :
                        'bg-orange-100 text-orange-800'
                      }`}>
                        {qualityText}
                      </span>
                    </div>
                    <p className="text-sm text-gray-600">
                      {timeUntil === 'now' ? 'Visible now' : `Visible ${timeUntil}`}
                    </p>
                  </div>

                  {/* Add to Calendar Button */}
                  <button
                    onClick={() => downloadICS(window, data.isoId)}
                    className="flex items-center gap-1 px-3 py-1.5 text-sm font-medium text-blue-700 bg-blue-50 hover:bg-blue-100 rounded-lg transition-colors"
                    title="Add to calendar"
                  >
                    <Download className="h-4 w-4" />
                    <span className="hidden sm:inline">Add</span>
                  </button>
                </div>

                {/* Window Details */}
                <div className="grid grid-cols-2 sm:grid-cols-3 gap-3 text-sm">
                  {/* Start Time */}
                  <div>
                    <div className="flex items-center gap-1 text-gray-600 mb-1">
                      <Clock className="h-3.5 w-3.5" />
                      <span className="text-xs font-medium">Start</span>
                    </div>
                    <p className="font-medium text-gray-900">
                      {startDate.toLocaleTimeString(undefined, {
                        hour: 'numeric',
                        minute: '2-digit',
                      })}
                    </p>
                  </div>

                  {/* End Time */}
                  <div>
                    <div className="flex items-center gap-1 text-gray-600 mb-1">
                      <Clock className="h-3.5 w-3.5" />
                      <span className="text-xs font-medium">End</span>
                    </div>
                    <p className="font-medium text-gray-900">
                      {endDate.toLocaleTimeString(undefined, {
                        hour: 'numeric',
                        minute: '2-digit',
                      })}
                    </p>
                  </div>

                  {/* Duration */}
                  <div>
                    <div className="flex items-center gap-1 text-gray-600 mb-1">
                      <TrendingUp className="h-3.5 w-3.5" />
                      <span className="text-xs font-medium">Duration</span>
                    </div>
                    <p className="font-medium text-gray-900">
                      {window.duration < 60
                        ? `${window.duration.toFixed(0)} min`
                        : `${(window.duration / 60).toFixed(1)} hr`}
                    </p>
                  </div>

                  {/* Max Altitude */}
                  <div className="col-span-2 sm:col-span-3">
                    <div className="text-xs font-medium text-gray-600 mb-1">
                      Max Altitude
                    </div>
                    <div className="flex items-center gap-2">
                      <div className="flex-grow bg-gray-200 rounded-full h-2">
                        <div
                          className={`h-2 rounded-full ${
                            window.maxAltitude > 60 ? 'bg-green-500' :
                            window.maxAltitude > 45 ? 'bg-blue-500' :
                            window.maxAltitude > 20 ? 'bg-yellow-500' :
                            'bg-orange-500'
                          }`}
                          style={{ width: `${(window.maxAltitude / 90) * 100}%` }}
                        ></div>
                      </div>
                      <span className="text-sm font-medium text-gray-900 min-w-[3rem] text-right">
                        {window.maxAltitude.toFixed(1)}°
                      </span>
                    </div>
                  </div>
                </div>
              </div>
            );
          })}
        </div>
      )}

      {/* Visibility Percentage */}
      {windows.length > 0 && (
        <div className="mt-4 pt-4 border-t border-gray-200">
          <div className="flex items-center justify-between text-sm">
            <span className="text-gray-600">
              Visible {data.forecast.visibilityPercentage.toFixed(0)}% of the time
            </span>
            <span className="text-gray-500">
              over next {data.forecastPeriod.days} days
            </span>
          </div>
        </div>
      )}
    </div>
  );
}
